// Swift-Objective-C Bridge Header for Object Capture
#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

// This header exposes Swift classes to Objective-C
// The actual interface will be generated by Swift compiler

NS_ASSUME_NONNULL_BEGIN

@interface ObjectCaptureViewController : UIViewController
- (instancetype)init;
@end

NS_ASSUME_NONNULL_END